### ISSUE TITLE
Core implementation

### ISSUE THREAD

**Issue by igorkamyshev** [purplenoodlesoop/flutter_effector#5]
Hello! One of the core features of effector (js-implementation) is internal scheduler for glitches handling (e.g. diamdon problem). Do you have any plans to port this scheduler?

**Comment by purplenoodlesoop** [comment]
Hi! 

The final goal is 1:1 feature wise port, so this feature will be ported too someday.

**Comment by igorkamyshev** [comment]
Thanks for answer. So, I've asked about it because, as I know, Effector based on this scheduling system. Possibly, feature-based port may be more complex, than concept-based port.

Did you think about port internal low level API and create library after that?

**Comment by igorkamyshev** [comment]
Sorry for the unsolicited advice. In my opinion, this project should be started with an internal core features. Public api (like createEvent) is the easiest part of Effector.

**Comment by AlexandrHoroshih** [comment]
it is actually, recommendation from the author of Effector (given somewhere in the effector's telegram chat) - that any port of Effector to any other enviroment should start with the kernel: https://github.com/effector/effector/blob/master/src/effector/kernel.ts

**Comment by purplenoodlesoop** [comment]
@igorkamyshev your advice is totally valid.

As it's stated in two places, in the description, and in the README, it's an experiment. It is not near any of its most vague form, not even a pre-alpha version.

Originally, I just wanted to see how the Effector API would look in the Flutter environment. And as I see it now – it looks nice and totally useful, and the core features will be implemented in the future.
